server:
  port: 23333

spring:
  application:
    name: doristest
  datasource:
    url: jdbc:mysql://10.247.53.18:9030/demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: cloudsea1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: doristest
      auto-offset-reset: latest
      max-poll-records: 20000
      enable-auto-commit: false
      auto-commit-interval: 1000

mybatis-plus:
  mapper-locations: classpath*:com/hyfly/doristest/**/mapper/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
