server:
  port: 22222

spring:
  application:
    name: zabbix2vm

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: kafka-test
      auto-offset-reset: latest
      max-poll-records: 20000
      enable-auto-commit: false
      auto-commit-interval: 1000

# victoriaMetrics 配置
victoriaMetrics:
  ip: 127.0.0.1
  port:
    base: 8428
    opentsdb: 4242
